version: '3'

services:

  redis:
    image: redis:latest
    ports:
       - "6001:6001"
    # networks:
    #   - lattice-network-1

  mongodb:
    image: mongo:latest
    ports:
       - "27001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - .\mongodb1_data:/data/db1
    # networks:
    #   - lattice-network-1

  api-server-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - mongodb
    # networks:
    #   - lattice-network-1

# networks:
#   lattice-network-1:
#     driver: bridge

volumes:
  mongodb1_data:
